---
- name: Deploy Spring Boot Application
  hosts: seed-hosts
  vars:
    app_name: skills-service
    ci_cd_namespace: puckboard-dw-ci-cd
    dev_namespace: puckboard-dw-dev
    test_namespace: puckboard-dw-test
    build:
      NAME: "{{app_name}}"
      PIPELINE_SOURCE_REPOSITORY_URL: https://github.com/dwasinge/optaplanner-poc.git
      PIPELINE_SOURCE_REPOSITORY_REF: master
      PIPELINE_CONTEXT_DIR: "{{app_name}}"
      S2I_BASE_IMAGE: redhat-openjdk18-openshift:1.4
    dev:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      SERVER_PORT: 8080
      MANAGEMENT_CONTEXT: /actuator
      MANAGEMENT_SERVER_PORT: 8081
    test:
      NAME: "{{app_name}}"
      PIPELINES_NAMESPACE: "{{ci_cd_namespace}}"
      SERVER_PORT: 8080
      MANAGEMENT_CONTEXT: /actuator
      MANAGEMENT_SERVER_PORT: 8081
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

