---
openshift_cluster_content:
- object: builds
  content:
  - name: "create application build pipeline"
    template: "{{ inventory_dir }}/../templates/binary-template-with-secrets.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - build
- object: secrets
  content:
  - name: "application key store secret"
    file: "{{ inventory_dir }}/../secrets/kie-server-secret.yml"
    namespace: "{{ dev_namespace }}"
    tags:
      - secret
      - dev-secrets
  - name: "application key store secret"
    file: "{{ inventory_dir }}/../secrets/kie-server-secret.yml"
    namespace: "{{ test_namespace }}"
    tags:
      - secret
      - test-secrets
- object: deployments
  content:
  - name: "deploy application to dev environment"
    template: "{{ inventory_dir }}/../templates/http-app-deploy-template.yml"
    params_from_vars: "{{ dev }}"
    namespace: "{{ dev_namespace }}"
    tags:
      - deployment
      - dev-deployments
  - name: "deploy application to test environment"
    template: "{{ inventory_dir }}/../templates/http-app-deploy-template.yml"
    params_from_vars: "{{ test }}"
    namespace: "{{ test_namespace }}"
    tags:
      - deployment
      - test-deployments
